[build]
  # This tells Netlify to change to the 'solana_forge' directory before running the build command.
  base = "solana_forge"

  # This is the command to build your frontend application.
  command = "pnpm run buildf"

  # This is the directory that contains the built files, relative to the 'base' directory.
  publish = ".next"